### ISSUE TITLE
Cannot run tests when using `commanded-ecto-projections`

### ISSUE THREAD

**Issue by imetallica** [commanded/commanded#119]
I'm having a hard time to figure out how to run tests using EventStore adapter instead of InMemory, since I'm using the ecto-projections library together.

The error I'm getting is the following:

```
12:30:47.180 [error] GenServer {Commanded.Registration.LocalRegistry, {Commanded.Event.Handler, "accounts_users"}} terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.5750.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (user_registry) lib/projections/ecto.ex:74: UserRegistry.Accounts.Projections.update_projection/3
    (commanded) lib/commanded/event/handler.ex:320: Commanded.Event.Handler.handle_event/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (commanded) lib/commanded/registration/registration.ex:290: Commanded.Event.Handler.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:events, [%Commanded.EventStore.RecordedEvent{causation_id: "fbe5aea4-1850-47b0-881a-b382e21831bb", correlation_id: "c782c8d1-f07b-4a2e-aeb0-84aa6a788db9", created_at: ~N[2017-12-26 14:30:47.134567], data: %UserRegistry.Accounts.Events.UserCreated{email: "foo@bar.com", hashed_password: "$pbkdf2-sha512$160000$o7EpzGeK.88mOwY69g/QFA$wtFzSNLXfypaH2NCEo9Ho.EuOMZbfpftJwmR/YbZ3PHQpLYx22qZnQlijpWrn1KX3pYmYaw35WA3VR/pHCXvHg"}, event_id: "e4dd2428-cada-4cea-9e2c-12fb4a699f38", event_number: 1, event_type: "Elixir.UserRegistry.Accounts.Events.UserCreated", metadata: %{}, stream_id: "foo@bar.com", stream_version: 1}]}
12:30:47.182 [error] GenServer {Commanded.Registration.LocalRegistry, {Commanded.Event.Handler, "accounts_users"}} terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.5813.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (user_registry) lib/projections/ecto.ex:74: UserRegistry.Accounts.Projections.update_projection/3
    (commanded) lib/commanded/event/handler.ex:320: Commanded.Event.Handler.handle_event/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (commanded) lib/commanded/registration/registration.ex:290: Commanded.Event.Handler.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:events, [%Commanded.EventStore.RecordedEvent{causation_id: "fbe5aea4-1850-47b0-881a-b382e21831bb", correlation_id: "c782c8d1-f07b-4a2e-aeb0-84aa6a788db9", created_at: ~N[2017-12-26 14:30:47.134567], data: %UserRegistry.Accounts.Events.UserCreated{email: "foo@bar.com", hashed_password: "$pbkdf2-sha512$160000$o7EpzGeK.88mOwY69g/QFA$wtFzSNLXfypaH2NCEo9Ho.EuOMZbfpftJwmR/YbZ3PHQpLYx22qZnQlijpWrn1KX3pYmYaw35WA3VR/pHCXvHg"}, event_id: "e4dd2428-cada-4cea-9e2c-12fb4a699f38", event_number: 1, event_type: "Elixir.UserRegistry.Accounts.Events.UserCreated", metadata: %{}, stream_id: "foo@bar.com", stream_version: 1}]}
12:30:47.183 [error] GenServer {Commanded.Registration.LocalRegistry, {Commanded.Event.Handler, "accounts_users"}} terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.5816.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (user_registry) lib/projections/ecto.ex:74: UserRegistry.Accounts.Projections.update_projection/3
    (commanded) lib/commanded/event/handler.ex:320: Commanded.Event.Handler.handle_event/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (commanded) lib/commanded/registration/registration.ex:290: Commanded.Event.Handler.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:events, [%Commanded.EventStore.RecordedEvent{causation_id: "fbe5aea4-1850-47b0-881a-b382e21831bb", correlation_id: "c782c8d1-f07b-4a2e-aeb0-84aa6a788db9", created_at: ~N[2017-12-26 14:30:47.134567], data: %UserRegistry.Accounts.Events.UserCreated{email: "foo@bar.com", hashed_password: "$pbkdf2-sha512$160000$o7EpzGeK.88mOwY69g/QFA$wtFzSNLXfypaH2NCEo9Ho.EuOMZbfpftJwmR/YbZ3PHQpLYx22qZnQlijpWrn1KX3pYmYaw35WA3VR/pHCXvHg"}, event_id: "e4dd2428-cada-4cea-9e2c-12fb4a699f38", event_number: 1, event_type: "Elixir.UserRegistry.Accounts.Events.UserCreated", metadata: %{}, stream_id: "foo@bar.com", stream_version: 1}]}
12:30:47.187 [error] GenServer {Commanded.Registration.LocalRegistry, {Commanded.Event.Handler, "accounts_users"}} terminating
** (DBConnection.OwnershipError) cannot find ownership process for #PID<0.5819.0>.

When using ownership, you must manage connections in one
of the four ways:

* By explicitly checking out a connection
* By explicitly allowing a spawned process
* By running the pool in shared mode
* By using :caller option with allowed process

The first two options require every new process to explicitly
check a connection out or be allowed by calling checkout or
allow respectively.

The third option requires a {:shared, pid} mode to be set.
If using shared mode in tests, make sure your tests are not
async.

The fourth option requires [caller: pid] to be used when
checking out a connection from the pool. The caller process
should already be allowed on a connection.

If you are reading this error, it means you have not done one
of the steps above or that the owner process has crashed.

    (db_connection) lib/db_connection.ex:926: DBConnection.checkout/2
    (db_connection) lib/db_connection.ex:742: DBConnection.run/3
    (db_connection) lib/db_connection.ex:790: DBConnection.transaction/3
    (ecto) lib/ecto/repo/queryable.ex:23: Ecto.Repo.Queryable.transaction/4
    (user_registry) lib/projections/ecto.ex:74: UserRegistry.Accounts.Projections.update_projection/3
    (commanded) lib/commanded/event/handler.ex:320: Commanded.Event.Handler.handle_event/2
    (elixir) lib/enum.ex:1826: Enum."-reduce/3-lists^foldl/2-0-"/3
    (commanded) lib/commanded/registration/registration.ex:290: Commanded.Event.Handler.handle_info/2
    (stdlib) gen_server.erl:616: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:686: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Last message: {:events, [%Commanded.EventStore.RecordedEvent{causation_id: "fbe5aea4-1850-47b0-881a-b382e21831bb", correlation_id: "c782c8d1-f07b-4a2e-aeb0-84aa6a788db9", created_at: ~N[2017-12-26 14:30:47.134567], data: %UserRegistry.Accounts.Events.UserCreated{email: "foo@bar.com", hashed_password: "$pbkdf2-sha512$160000$o7EpzGeK.88mOwY69g/QFA$wtFzSNLXfypaH2NCEo9Ho.EuOMZbfpftJwmR/YbZ3PHQpLYx22qZnQlijpWrn1KX3pYmYaw35WA3VR/pHCXvHg"}, event_id: "e4dd2428-cada-4cea-9e2c-12fb4a699f38", event_number: 1, event_type: "Elixir.UserRegistry.Accounts.Events.UserCreated", metadata: %{}, stream_id: "foo@bar.com", stream_version: 1}]}
```

**Comment by slashdotdash** [comment]
@imetallica Are you using the Ecto Sandbox adapter for your tests? If so you will need to use the following shared checkout mode:

```elixir
:ok = Ecto.Adapters.SQL.Sandbox.checkout(MyApp.Repo)

Ecto.Adapters.SQL.Sandbox.mode(MyApp.Repo, {:shared, self()})
```

In the Conduit sample application there's a branch where I've configured both the in-memory event store and Ecto Sandbox: https://github.com/slashdotdash/conduit/commits/feature/in-memory-tests

Another approach is to reset your read model database by truncating any affected tables in the ExUnit `setup` function. There's an example of this approach in the [Conduit sample application](https://github.com/slashdotdash/conduit]. It defines a `DataCase` module that is an ExUnit case template for use by any test that modifies the read model database. The `setup` function resets both the event store and read store databases before executing each test.

**Comment by imetallica** [comment]
@slashdotdash it worked! But I got a question. I'm trying to do the following test:
```
  describe "Accounts interactions" do
    test "create user.", %{} do
      assert :ok == Accounts.create_client(@create_client_attrs)
      assert {:error, "An account with this email already exists"} == Accounts.create_client(@create_client_attrs)
      assert {:error, "Invalid params given."} == Accounts.create_client(Map.put(@create_client_attrs, "email", "invalid email"))
    end
  end
```

This timeouts in the second assertion, I guess because it does not commit anything on the eventstore, right? The better way to test it might be the "another approach" right?

**Comment by slashdotdash** [comment]
@imetallica Your test looks ok, do you have the command validation configured? 

If you're using dispatch middleware, such as this [validate example](https://github.com/slashdotdash/conduit/blob/1800843688fa82e520c7ec7b0a0407f78f982a59/lib/conduit/support/middleware/validate.ex) from Conduit, you need to configure it in the router.

```elixir
defmodule MyRouter do
  use Commanded.Commands.Router

  middleware Validate
end
```

**Comment by slashdotdash** [comment]
@imetallica Feel free to join the Gitter [Commanded chat room](https://gitter.im/commanded/Lobby) to discuss more easily.

**Comment by Freyskeyd** [comment]
@imetallica can we close this issue?

**Comment by imetallica** [comment]
@Freyskeyd yeah sure, let me close it.
