### ISSUE TITLE
Make commanded gracefully retry connection instead of shutting down

### ISSUE THREAD

**Issue by drozzy** [commanded/commanded#202]
When I start my up without eventstore connection, my Extreme library correctly tries to reconnect:

```
[warn] Error connecting to EventStore @ localhost:1113. Will retry in 2000 ms.
```

But commanded just shuts down. So now I have an app that is in an inconsistent state (it would be better if commanded was either started as part of the app supervisor or it would keep retrying):

```
[warn] Error connecting to EventStore @ localhost:1113. Will retry in 2000 ms.
[error] GenServer Commanded.EventStore.Adapters.Extreme.EventPublisher terminating
** (stop) exited in: GenServer.call(Commanded.EventStore.Adapters.Extreme.EventStore, {:subscribe_to, #PID<0.316.0>, "$streams", true}, 5000)
    ** (EXIT) time out
    (elixir) lib/gen_server.ex:924: GenServer.call/3
    (commanded_extreme_adapter) lib/extreme/event_publisher.ex:2: Commanded.EventStore.Adapters.Extreme.EventPublisher.handle_cast/2
...
```

**Comment by slashdotdash** [comment]
This will need to be addressed in #117 which will allow you to define, start, and supervise your own Commanded applications (similar to Ecto's `Repo` module).
