### ISSUE TITLE
the process is not alive when dispatching command

### ISSUE THREAD

**Issue by gen1321** [commanded/commanded#306]
Hello! I run into some troubles with commanded and conduit example app. I followed getting started guide, and when I did try to dispatch command I got following error

```elixir 

iex(1)> FleetlyCallbacks.CallbackRouter.dispatch(%FleetlyCallbacks.Commands.CreateCallback{access_token: 'test', name: 'test'})
23:30:50.271 [debug] Locating aggregate process for `FleetlyCallbacks.Callback` with UUID "test"
iex(2)> 
23:30:50.300 [error] Task #PID<0.248.0> started from #PID<0.242.0> terminating
** (stop) exited in: GenServer.call({:via, Registry, {Commanded.Registration.LocalRegistry, {FleetlyCallbacks.Callback, "test"}}}, {:execute_command, %Commanded.Aggregates.ExecutionContext{causation_id: "dfb0d90d-309b-4ce4-9085-f6485de1e6b9", command: %FleetlyCallbacks.Commands.CreateCallback{access_token: 'teset', name: 'test'}, correlation_id: "b863bc5f-d683-43f0-ab05-a099b33458f8", function: :execute, handler: FleetlyCallbacks.Callback, lifespan: Commanded.Aggregates.DefaultLifespan, metadata: %{}, retry_attempts: 10}}, 5000)
    ** (EXIT) no process: the process is not alive or there's no process currently associated with the given name, possibly because its application isn't started
    (elixir) lib/gen_server.ex:999: GenServer.call/3
    (elixir) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Commanded.Aggregates.Aggregate.execute/4
    Args: [FleetlyCallbacks.Callback, "test", %Commanded.Aggregates.ExecutionContext{causation_id: "dfb0d90d-309b-4ce4-9085-f6485de1e6b9", command: %FleetlyCallbacks.Commands.CreateCallback{access_token: 'teset', name: 'test'}, correlation_id: "b863bc5f-d683-43f0-ab05-a099b33458f8", function: :execute, handler: FleetlyCallbacks.Callback, lifespan: Commanded.Aggregates.DefaultLifespan, metadata: %{}, retry_attempts: 10}, 5000]
```

I thought that maybe I'm doing something wrong so I tried to run test suit in [conduit app](https://github.com/slashdotdash/conduit) and got same error on almost all tests. 

I tried it both with elixir 1.9.1 and 1.7.4 and got the same results

**Comment by gen1321** [comment]
Oh, so I guess it was happening because of OTP version. upgrading to latest otp version helps

**Comment by slashdotdash** [comment]
@gen1321 Which version of OTP didn't work? I'll update the README to clarify minimum required version.

**Comment by gen1321** [comment]
I think it was otp 19

**Comment by slashdotdash** [comment]
Added requirement for Erlang v21.0 to README in d05b71858409fcf0676975edabe109d4a203da15.
