### ISSUE TITLE
Snapshot is being deserialized before snapshot_module_version is validated

### ISSUE THREAD

**Issue by EskiMag** [commanded/commanded#373]
I am using custom serializer for my `EventStore`.
The `deserialize/2` function is unable to deserialize a snapshot with `snapshot_module_version = n - 1` if `snapshot_version` in the `snapshotting` configuration is equal to `n`. In other words: it's not backward compatible.

Currently, when trying to read snapshot when rebuilding aggregate state, the snapshot is read, deserialized and the version is checked against the configured one.
Of course, this doesn't work for me, because as soon as the snapshot is sent to the `deserialize/2` function, it raises an exception.

I am not sure if I am using the custom serializer incorrectly, so please correct me, if I am wrong. I thought that the snapshot retrieval could use some JSON(B) querying to return `nil` if there's no snapshot in the EventStore with the current version.
This could skip the useless deserialization if the snapshot is already old.

If I am thinking correctly, I could try to implement this myself. If not, then thanks for the clarification in advance. :-)

**Comment by razielgn** [comment]
I have also run into this, when implementing `Commanded.Serialization.JsonDecoder` on an aggregate.
I was expecting the snapshot gets discarded when incrementing `snapshot_module_version`.

Here's a simple example to reproduce:

`snapshot_module_version = 1, snapshot_every = 1`
```elixir
defmodule Example.Aggregates.Foo do
  alias Example.Commands.CreateWallet

  alias Example.Events.WalletCreated

  @derive Jason.Encoder
  defstruct id: nil

  def execute(%__MODULE__{id: nil}, %CreateWallet{wallet_id: wallet_id}) do
    %WalletCreated{wallet_id: wallet_id}
  end

  def execute(%__MODULE__{id: wallet_id}, %CreateWallet{wallet_id: wallet_id}) do
    {:error, :already_exists}
  end

  def apply(%__MODULE__{} = state, %WalletCreated{wallet_id: wallet_id}) do
    %__MODULE__{state | id: wallet_id}
  end
end
```

Then dispatch with

```elixir
Example.dispatch(%CreateWallet{wallet_id: "257cb4bc-aeac-4793-8fd8-7e10df4faa93"})
```

Then update the aggregate's code with

`snapshot_module_version = 2, snapshot_every = 1`
```elixir
defmodule Example.Aggregates.Foo do
  alias Example.Commands.CreateWallet

  alias Example.Events.WalletCreated

  @derive Jason.Encoder
  defstruct id: nil, foo: :bar

  def execute(%__MODULE__{id: nil}, %CreateWallet{wallet_id: wallet_id}) do
    %WalletCreated{wallet_id: wallet_id}
  end

  def execute(%__MODULE__{id: wallet_id}, %CreateWallet{wallet_id: wallet_id}) do
    {:error, :already_exists}
  end

  def apply(%__MODULE__{} = state, %WalletCreated{wallet_id: wallet_id}) do
    %__MODULE__{state | id: wallet_id}
  end

  defimpl Commanded.Serialization.JsonDecoder do
    alias Example.Aggregates.Foo, as: Aggregate

    def decode(%Aggregate{foo: foo} = state) do
      %Aggregate{state | foo: String.to_existing_atom(foo)}
    end
  end
end
```

It's enough to re-dispatch the same command as above to get a crash:

```
** (stop) exited in: GenServer.call({:via, Registry, {Example.LocalRegistry, {Example, Example.Aggregates.Foo, "257cb4bc-aeac-4793-8fd8-7e10df4faa93"}}}, {:execute_command, %Commanded.Aggregates.ExecutionContext{command: %Example.Commands.CreateWallet{wallet_id: "257cb4bc-aeac-4793-8fd8-7e10df4faa93"}, causation_id: "1344e5ea-a36f-468b-aa1b-113bb230b139", correlation_id: "e97dd82e-b3d9-4411-a776-9325975b3b69", handler: Example.Aggregates.Foo, function: :execute, before_execute: nil, retry_attempts: 10, returning: false, lifespan: Commanded.Aggregates.DefaultLifespan, metadata: %{}}}, 5000)
    ** (EXIT) an exception was raised:
        ** (ArgumentError) errors were found at the given arguments:

  * 1st argument: not a binary

            :erlang.binary_to_existing_atom(:bar, :utf8)
            (example 0.1.0) lib/example/aggregates/foo.ex:33: Commanded.Serialization.JsonDecoder.Example.Aggregates.Foo.decode/1
            (eventstore 1.4.4) lib/event_store/snapshots/snapshot_data.ex:34: EventStore.Snapshots.SnapshotData.deserialize/2
            (eventstore 1.4.4) lib/event_store/snapshots/snapshotter.ex:14: EventStore.Snapshots.Snapshotter.read_snapshot/3
            (commanded_eventstore_adapter 1.4.0) lib/commanded/event_store/adapters/event_store.ex:121: Commanded.EventStore.Adapters.EventStore.read_snapshot/2
            (commanded 1.4.2) lib/commanded/event_store.ex:286: anonymous fn/2 in Commanded.EventStore.span/3
            (telemetry 1.2.1) /home/user/example/deps/telemetry/src/telemetry.erl:321: :telemetry.span/3
            (commanded 1.4.2) lib/commanded/snapshotting.ex:29: Commanded.Snapshotting.read_snapshot/1
            (commanded 1.4.2) lib/commanded/aggregates/aggregate_state_builder.ex:22: Commanded.Aggregates.AggregateStateBuilder.populate/1
            (commanded 1.4.2) lib/commanded/aggregates/aggregate.ex:270: Commanded.Aggregates.Aggregate.handle_continue/2
            (stdlib 5.2) gen_server.erl:1085: :gen_server.try_handle_continue/3
            (stdlib 5.2) gen_server.erl:995: :gen_server.loop/7
            (stdlib 5.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    (elixir 1.16.0) lib/gen_server.ex:1114: GenServer.call/3
    (commanded 1.4.2) lib/commanded/aggregates/aggregate.ex:194: Commanded.Aggregates.Aggregate.execute/5
    (elixir 1.16.0) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
    (elixir 1.16.0) lib/task/supervised.ex:36: Task.Supervised.reply/4
Function: &Commanded.Aggregates.Aggregate.execute/5
    Args: [Example, Example.Aggregates.Foo, "257cb4bc-aeac-4793-8fd8-7e10df4faa93", %Commanded.Aggregates.ExecutionContext{command: %Example.Commands.CreateWallet{wallet_id: "257cb4bc-aeac-4793-8fd8-7e10df4faa93"}, causation_id: "1344e5ea-a36f-468b-aa1b-113bb230b139", correlation_id: "e97dd82e-b3d9-4411-a776-9325975b3b69", handler: Example.Aggregates.Foo, function: :execute, before_execute: nil, retry_attempts: 10, returning: false, lifespan: Commanded.Aggregates.DefaultLifespan, metadata: %{}}, 5000]
```

So yeah, deserialization is performed before checking that `snapshot_module_version` matches.
