### ISSUE TITLE
no function clause matching in Commanded.Event.Handler.partition_event/4

### ISSUE THREAD

**Issue by jdav-dev** [commanded/commanded#540]
It seems that `Commanded.Event.Handler.partition_event/4` is expecting a `%Commanded.EventStore.RecordedEvent{}` struct as its first argument, but is receiving a `%EventStore.RecordedEvent{}` struct instead.  I'm not sure if this is an issue with how I configured Commanded and EventStore, or a bug.  Any help is appreciated.

Here's the stacktrace, running Commanded 1.4.2 and EventStore 1.4.2:

```
** (FunctionClauseError) no function clause matching in Commanded.Event.Handler.partition_event/4
    (commanded 1.4.2) lib/commanded/event/handler.ex:1096: Commanded.Event.Handler.partition_event(%EventStore.RecordedEvent{event_number: 1, event_id: "d002e51f-05a9-4f7f-9122-0eb7e789dccc", stream_uuid: "1bae5f15-5046-4f8b-a9a2-77e51f650396", stream_version: 1, correlation_id: "e6938410-cf5f-4c21-8fa5-950578aaafd7", causation_id: "2039699e-abfc-4f44-9ac3-eea76c19de38", event_type: "Elixir.MyApp.MyEvent", data: #MyApp.MyEvent<...>, metadata: %{}, created_at: ~U[2023-08-30 18:32:38.802873Z]}, MyApp.Commanded, "MyApp.MyEventHandler", MyApp.MyEventHandler)
    (eventstore 1.4.2) lib/event_store/subscriptions/subscription_fsm.ex:502: EventStore.Subscriptions.SubscriptionFsm.enqueue_event/3
    (eventstore 1.4.2) lib/event_store/subscriptions/subscription_fsm.ex:484: EventStore.Subscriptions.SubscriptionFsm.enqueue_events/2
    (eventstore 1.4.2) lib/event_store/subscriptions/subscription_fsm.ex:433: EventStore.Subscriptions.SubscriptionFsm.catch_up_from_stream/1
    (eventstore 1.4.2) lib/event_store/subscriptions/subscription_fsm.ex:98: EventStore.Subscriptions.SubscriptionFsm.transition/3
    (eventstore 1.4.2) lib/event_store/subscriptions/subscription.ex:186: EventStore.Subscriptions.Subscription.handle_cast/2
    (stdlib 5.0.2) gen_server.erl:1103: :gen_server.try_handle_cast/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
    (elixir 1.15.4) lib/gen_server.ex:1074: GenServer.call/3
```

**Comment by jdav-dev** [comment]
This one was on me.  `commanded-eventstore-adapter` was version `1.2.0`, while `1.4.0` [added support for subscription concurrency](https://github.com/commanded/commanded-eventstore-adapter/pull/10).
