### ISSUE TITLE
Help needed: Process Manager causes `unknown registry` error when running tests

### ISSUE THREAD

**Issue by robdembitel** [commanded/commanded#602]
Hello there,

first of all, thanks for the awesome work on this library. I use it daily to do the bread and butter of my CQRS/ES application.

I added a Process Manager to my app, which is subscribed to `Event A` and produces a new Command `Command B` when `Event A` occurs - so nothing special, same as described in the docs. When running the app, inside of `iex -S mix phx.server` all works fine.

Now, when running my test suite, although all my tests pass, I get the following error in the logs.

````
[error] GenServer {MyApp.EventStore.EventStore.Subscriptions.Registry, {"$all", "MyApp.Jobs.Managers.Jobs"}} terminating
** (ArgumentError) unknown registry: MyApp.EventStore.EventStore.PubSub
    (elixir 1.15.4) lib/registry.ex:1391: Registry.info!/1
    (elixir 1.15.4) lib/registry.ex:1007: Registry.register/3
    (eventstore 1.4.6) lib/event_store/pubsub.ex:38: EventStore.PubSub.subscribe/3
    (eventstore 1.4.6) lib/event_store/subscriptions/subscription_fsm.ex:70: EventStore.Subscriptions.SubscriptionFsm.transition/3
    (eventstore 1.4.6) lib/event_store/subscriptions/subscription.ex:221: EventStore.Subscriptions.Subscription.handle_call/3
    (stdlib 5.0.2) gen_server.erl:1113: :gen_server.try_handle_call/4
    (stdlib 5.0.2) gen_server.erl:1142: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message (from #PID<0.27408.0>): {:connect, #PID<0.27408.0>, [retry_interval: 60000, hibernate_after: 15000, partition_by: nil, concurrency_limit: 1, name: MyApp.EventStore, mapper: &Commanded.EventStore.Adapters.EventStore.Mapper.from_recorded_event/1, conn: MyApp.EventStore.Postgrex, event_store: MyApp.EventStore, query_timeout: 15000, schema: "public", serializer: Commanded.Serialization.JsonSerializer, stream_uuid: "$all", subscription_name: "MyApp.Jobs.Managers.Jobs", start_from: 0]}
````

These are the relevant parts in my config.exs

````
config :my_app,
  ecto_repos: [MyApp.Repo],
  event_stores: [MyApp.EventStore]

config :my_app, MyApp.App,
  event_store: [
    adapter: Commanded.EventStore.Adapters.EventStore,
    event_store: MyApp.EventStore
  ],
  pubsub: [
    phoenix_pubsub: [
      adapter: Phoenix.PubSub.PG2,
      pool_size: 1
    ]
  ],
  registry: :global

config :commanded,
  event_store_adapter: Commanded.EventStore.Adapters.EventStore
```` 

What's strange is: When running the app locally, all is fine. Only in tests this error occurs in the log.

I even checked the example app (https://github.com/slashdotdash/conduit/blob/master/README.md) to see if I am missing any relevant configuration - no luck.

Help is much appreciated <3

**Comment by robdembitel** [comment]
After some more investigation and diving into the code, I could narrow it down to this:

When adding the option `start_from: :current` to the beginning of the process manager, it causes the error in the logs when running the tests.

```
  use Commanded.ProcessManagers.ProcessManager,
    application: MyApp.App,
    name: "MyApp.Jobs.Managers.Jobs",
    start_from: :current
``` 

whereas changing the `start_from` to `:origin` or leaving it out all together makes the error disappear from the logs, like this:

```
  use Commanded.ProcessManagers.ProcessManager,
    application: MyApp.App,
    name: "MyApp.Jobs.Managers.Jobs"
``` 

Maybe I am doing the configuration wrong (for my tests) - How can I configure the process manager to only pick up new events instead of starting at the beginning of the event stream?

**Comment by robdembitel** [comment]
@datafoo yes I still have this issue. I am also not sure that my initial "fix" above actually fixed it in the first place.

I actually tried a couple of times to fix it, but so far I could not track down the exact cause of this error in the logs.

**Comment by robdembitel** [comment]
yes it seems to be fixed.

thanks for the support!
